server:
  http:
    addr: 127.0.0.1:8000
  grpc:
    addr: 127.0.0.1:9000
  ext_fields:
    - ip
    - ua
    - rid
    - ck
    - ts
  topic_whitelist: topic_whitelist.txt
kafka:
  broker:
    - localhost:9092
  partition_cnt: 1
  ack_policy: 1
  write_timeout: 3
data:
  data_dir: /tmp/vftt
log:
  log_dir: /var/logs/vftt
  log_level: disable