// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.11.4
// source: api.proto

// 默认包名

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Api_IntakeData_FullMethodName      = "/visforest.vftt.protobuf.api.Api/IntakeData"
	Api_BatchIntakeData_FullMethodName = "/visforest.vftt.protobuf.api.Api/BatchIntakeData"
	Api_MixIntakeData_FullMethodName   = "/visforest.vftt.protobuf.api.Api/MixIntakeData"
)

// ApiClient is the client API for Api service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApiClient interface {
	// 单条数据摄入
	IntakeData(ctx context.Context, in *IntakeDataRequest, opts ...grpc.CallOption) (*IntakeDataResponse, error)
	// 同 topic 的数据批量摄入
	BatchIntakeData(ctx context.Context, in *BatchIntakeDataRequest, opts ...grpc.CallOption) (*BatchIntakeDataResponse, error)
	// 不同 topic 的数据批量摄入
	MixIntakeData(ctx context.Context, in *MixIntakeDataRequest, opts ...grpc.CallOption) (*MixIntakeDataResponse, error)
}

type apiClient struct {
	cc grpc.ClientConnInterface
}

func NewApiClient(cc grpc.ClientConnInterface) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) IntakeData(ctx context.Context, in *IntakeDataRequest, opts ...grpc.CallOption) (*IntakeDataResponse, error) {
	out := new(IntakeDataResponse)
	err := c.cc.Invoke(ctx, Api_IntakeData_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) BatchIntakeData(ctx context.Context, in *BatchIntakeDataRequest, opts ...grpc.CallOption) (*BatchIntakeDataResponse, error) {
	out := new(BatchIntakeDataResponse)
	err := c.cc.Invoke(ctx, Api_BatchIntakeData_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) MixIntakeData(ctx context.Context, in *MixIntakeDataRequest, opts ...grpc.CallOption) (*MixIntakeDataResponse, error) {
	out := new(MixIntakeDataResponse)
	err := c.cc.Invoke(ctx, Api_MixIntakeData_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiServer is the server API for Api service.
// All implementations must embed UnimplementedApiServer
// for forward compatibility
type ApiServer interface {
	// 单条数据摄入
	IntakeData(context.Context, *IntakeDataRequest) (*IntakeDataResponse, error)
	// 同 topic 的数据批量摄入
	BatchIntakeData(context.Context, *BatchIntakeDataRequest) (*BatchIntakeDataResponse, error)
	// 不同 topic 的数据批量摄入
	MixIntakeData(context.Context, *MixIntakeDataRequest) (*MixIntakeDataResponse, error)
	mustEmbedUnimplementedApiServer()
}

// UnimplementedApiServer must be embedded to have forward compatible implementations.
type UnimplementedApiServer struct {
}

func (UnimplementedApiServer) IntakeData(context.Context, *IntakeDataRequest) (*IntakeDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IntakeData not implemented")
}
func (UnimplementedApiServer) BatchIntakeData(context.Context, *BatchIntakeDataRequest) (*BatchIntakeDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchIntakeData not implemented")
}
func (UnimplementedApiServer) MixIntakeData(context.Context, *MixIntakeDataRequest) (*MixIntakeDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MixIntakeData not implemented")
}
func (UnimplementedApiServer) mustEmbedUnimplementedApiServer() {}

// UnsafeApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApiServer will
// result in compilation errors.
type UnsafeApiServer interface {
	mustEmbedUnimplementedApiServer()
}

func RegisterApiServer(s grpc.ServiceRegistrar, srv ApiServer) {
	s.RegisterService(&Api_ServiceDesc, srv)
}

func _Api_IntakeData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntakeDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).IntakeData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_IntakeData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).IntakeData(ctx, req.(*IntakeDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_BatchIntakeData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchIntakeDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).BatchIntakeData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_BatchIntakeData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).BatchIntakeData(ctx, req.(*BatchIntakeDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_MixIntakeData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MixIntakeDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).MixIntakeData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_MixIntakeData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).MixIntakeData(ctx, req.(*MixIntakeDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Api_ServiceDesc is the grpc.ServiceDesc for Api service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Api_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "visforest.vftt.protobuf.api.Api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IntakeData",
			Handler:    _Api_IntakeData_Handler,
		},
		{
			MethodName: "BatchIntakeData",
			Handler:    _Api_BatchIntakeData_Handler,
		},
		{
			MethodName: "MixIntakeData",
			Handler:    _Api_MixIntakeData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
